# Estagio 1 - Será responsavel em construir nossa aplicação
FROM node:latest AS build
WORKDIR /usr/app/frontend
COPY package.json ./
RUN yarn install
COPY . .
EXPOSE 4200
RUN yarn build

# Estagio 2 - Será responsavel por expor a aplicação
FROM nginx:latest
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/frontend/dist/frontend /usr/share/nginx/html